import{a as y,i as m,S as L}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();async function f(o,t){const a=`https://pixabay.com/api/?${new URLSearchParams({key:"43103378-6af8ee9eb079e11667ecfffdc",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:t})}`;try{const e=await y.get(a);return console.log(e.data),e.data}catch(e){console.log(e)}}function p(o,t,c,a){if(o.length<=0){c.classList.add("is-hidden"),a.classList.add("is-hidden"),m.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});return}const e=o.map(r=>`
          <li class="cards">
          <a href="${r.largeImageURL}"> <img src="${r.webformatURL}" alt="${r.tags}" width="360" height="152"/> </a>
          <div class="card-description">
            <p class="description"><b>Likes</b> ${r.likes}</p>
            <p class="description"><b>Views</b> ${r.views}</p>
            <p class="description"><b>Comments</b> ${r.comments}</p>
            <p class="description"><b>Downloads</b> ${r.downloads}</p>
            </div>
          </li>
      `).join("");t.insertAdjacentHTML("beforeend",e);const s=new L(".gallery a",{captionsData:"alt",captionDelay:250});c.classList.add("is-hidden"),a.classList.remove("is-hidden"),s.refresh()}function b(){return document.querySelector(".cards").getBoundingClientRect().height}const d=document.querySelector("#data-input"),u=document.querySelector(".gallery"),i=document.querySelector(".loader");document.querySelector(".footer-loader");const v=document.querySelector("form"),n=document.querySelector(".load-btn");let l=1,h=0;const w=15;n.classList.add("is-hidden");v.addEventListener("submit",async o=>{if(o.preventDefault(),i.classList.remove("is-hidden"),u.innerHTML="",l=1,d.value===""){m.show({title:"Error",message:"Please, fill the field to start search images. ",backgroundColor:"#ef4040",position:"topRight"});return}try{const t=await f(d.value);h=Math.ceil(t.totalHits/w),p(t.hits,u,i,n),g()}catch(t){console.log(t)}});n.addEventListener("click",async o=>{o.preventDefault(),i.classList.add("footer-loader"),i.classList.remove("is-hidden"),l+=1;try{const t=await f(d.value,l);p(t.hits,u,i,n),window.scrollBy({top:b()*2,left:0,behavior:"smooth"}),g()}catch(t){console.log(t)}});function g(){l>=h?(n.classList.add("is-hidden"),m.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#ef4040",position:"topRight"})):n.classList.remove("is-hidden"),i.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
