import{a as p,i as u,S as f}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function m(o,t){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"43103378-6af8ee9eb079e11667ecfffdc",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:t})}`;try{return(await p.get(i)).data}catch{console.log(error)}}function g(o,t,a,i){if(o.length<=0){a.classList.add("is-hidden"),i.classList.add("is-hidden"),u.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});return}const e=o.map(r=>`
          <li class="cards">
          <a href="${r.largeImageURL}"> <img src="${r.webformatURL}" alt="${r.tags}" width="360" height="152"/> </a>
          <div class="card-description">
            <p class="description"><b>Likes</b> ${r.likes}</p>
            <p class="description"><b>Views</b> ${r.views}</p>
            <p class="description"><b>Comments</b> ${r.comments}</p>
            <p class="description"><b>Downloads</b> ${r.downloads}</p>
            </div>
          </li>
      `).join("");t.insertAdjacentHTML("beforeend",e);const s=new f(".gallery a",{captionsData:"alt",captionDelay:250});a.classList.add("is-hidden"),i.classList.remove("is-hidden"),s.refresh()}const n=document.querySelector("#data-input"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector("form");d.addEventListener("submit",o=>{if(o.preventDefault(),console.log("1"),l.classList.remove("is-hidden"),c.innerHTML="",n.value===""){u.show({title:"Error",message:"Please, fill the field to start search images. ",backgroundColor:"#ef4040",position:"topRight"});return}m(n.value).then(t=>g(t.hits,c,l)).catch(t=>console.log(t)),d.reset()});
//# sourceMappingURL=commonHelpers.js.map
